name: Build docker image

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Install SSH key of bastion
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_nice
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host nice
              HostName 51.255.234.46
              User gitlab-ci
              IdentityFile ~/.ssh/id_nice
    
      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: 'ssh://nice'
          context_name: 'dev-server'
      - run: docker --context dev-server ps
