name: Build docker image

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: 'ssh://gitlab-ci@services-dev.logitud.fr'
          context_name: 'dev-server'
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}
      - run: docker --context dev-server ps
